#!/bin/bash
if [ "$1" == "" ]; then
  ./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests
else
  if [ -f "$1" ]; then
    ./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox $1
  else
    ./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests/*$1*
  fi
fi
